//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tAccion
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tAsignacionResponsable
{
    public decimal id { get; set; }
    public Nullable<decimal> idResponsable { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<decimal> idAsigno { get; set; }
    public Nullable<decimal> idPedido { get; set; }
    public string Comentario { get; set; }
}

public partial class tCategoria
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tCategoriaInventario
{
    public decimal id { get; set; }
    public string descripcion { get; set; }
    public string numero { get; set; }
    public string contador { get; set; }
}

public partial class tCliente
{
    public decimal id { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public string Nombre { get; set; }
    public string Interno { get; set; }
    public string Mail { get; set; }
    public string Ip { get; set; }
    public string Password { get; set; }
    public string UsuarioRed { get; set; }
    public string PasswordRed { get; set; }
    public string ClaveSistema { get; set; }
    public Nullable<short> Papelera { get; set; }
    public Nullable<short> Autorizado { get; set; }
}

public partial class tClientePosible
{
    public decimal id { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public string rubro { get; set; }
    public string contacto { get; set; }
    public string puestoContacto { get; set; }
    public string contactoVinculado { get; set; }
    public string Mail { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<decimal> idAccion1 { get; set; }
    public Nullable<short> idEstadoAccion1 { get; set; }
    public Nullable<decimal> idAccion2 { get; set; }
    public Nullable<short> idEstadoAccion2 { get; set; }
    public Nullable<decimal> idAccion3 { get; set; }
    public Nullable<short> idEstadoAccion3 { get; set; }
    public Nullable<decimal> idAccion4 { get; set; }
    public Nullable<short> idEstadoAccion4 { get; set; }
    public Nullable<decimal> idEstado { get; set; }
}

public partial class tComentario
{
    public decimal id { get; set; }
    public Nullable<decimal> idPedido { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public string Descripcion { get; set; }
    public Nullable<bool> VisibilidadCliente { get; set; }
    public string Tipo { get; set; }
}

public partial class tComentarioCompra
{
    public decimal id { get; set; }
    public Nullable<decimal> idCompra { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public string Descripcion { get; set; }
    public string Tipo { get; set; }
}

public partial class tCompra
{
    public decimal id { get; set; }
    public Nullable<decimal> idPedido { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public Nullable<decimal> idCliente { get; set; }
    public Nullable<decimal> idEstado { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<decimal> totalProveedor { get; set; }
    public Nullable<decimal> totalCliente { get; set; }
    public Nullable<byte> iva { get; set; }
    public string codigo { get; set; }
    public Nullable<int> NewId { get; set; }
}

public partial class tDatosTecnicos
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tEmpresa
{
    public decimal id { get; set; }
    public string Nombre { get; set; }
    public string Direccion { get; set; }
    public string Telefono { get; set; }
    public string Datos { get; set; }
    public Nullable<short> Papelera { get; set; }
    public string Cuit { get; set; }
    public string DominioMail { get; set; }
}

public partial class tEstado
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tEstadoCompra
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tImagen
{
    public decimal id { get; set; }
    public string descripcion { get; set; }
    public byte[] imagen { get; set; }
}

public partial class tInventario
{
    public decimal id { get; set; }
    public Nullable<decimal> idImagen { get; set; }
    public Nullable<decimal> idCategoria { get; set; }
    public string descripcion { get; set; }
    public Nullable<int> empresa { get; set; }
    public string nro { get; set; }
    public Nullable<decimal> valor { get; set; }
    public Nullable<int> cantUnidades { get; set; }
    public Nullable<decimal> idResponsable { get; set; }
}

public partial class tItem
{
    public decimal id { get; set; }
    public Nullable<int> cantidad { get; set; }
    public string descripcion { get; set; }
    public Nullable<decimal> importeProveedor { get; set; }
    public Nullable<decimal> importeCliente { get; set; }
    public Nullable<decimal> idProveedor { get; set; }
    public Nullable<decimal> idCompra { get; set; }
    public Nullable<decimal> NroPedidoProveedor { get; set; }
}

public partial class tItem2
{
    public decimal id { get; set; }
    public Nullable<decimal> idPedido { get; set; }
    public string Nombre { get; set; }
    public string Descripcion { get; set; }
    public Nullable<int> Cantidad { get; set; }
    public string Costo { get; set; }
    public string Precio { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<byte> idEstado { get; set; }
    public Nullable<decimal> idAprobo { get; set; }
}

public partial class tLog
{
    public decimal id { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public string Accion { get; set; }
    public string Mensaje { get; set; }
}

public partial class tManual
{
    public decimal id { get; set; }
    public string titulo { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public Nullable<byte> Papelera { get; set; }
    public string descripcion { get; set; }
}

public partial class tModoResolucion
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tNovedad
{
    public decimal id { get; set; }
    public string descripcion { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
}

public partial class tPedido
{
    public decimal id { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public Nullable<decimal> idCliente { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public string Titulo { get; set; }
    public string Descripcion { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public Nullable<System.DateTime> FechaARealizar { get; set; }
    public Nullable<byte> Estado { get; set; }
    public Nullable<decimal> idCategoria { get; set; }
    public Nullable<byte> idPrioridad { get; set; }
    public Nullable<decimal> idAsignacionResponsable { get; set; }
    public Nullable<byte> idModoResolucion { get; set; }
}

public partial class tPedidoMail
{
    public decimal id { get; set; }
    public Nullable<decimal> idPedido { get; set; }
    public string nroMail { get; set; }
    public Nullable<System.DateTime> fecha { get; set; }
}

public partial class tPrioridad
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
}

public partial class tProveedor
{
    public decimal id { get; set; }
    public string Nombre { get; set; }
    public string Telefono { get; set; }
    public string Direccion { get; set; }
    public string Mail { get; set; }
    public Nullable<byte> Papelera { get; set; }
}

public partial class tRegistroAcceso
{
    public decimal id { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
    public string descripcion { get; set; }
    public string ip { get; set; }
}

public partial class tResponsableEmpresa
{
    public decimal id { get; set; }
    public Nullable<decimal> idEmpresa { get; set; }
    public Nullable<decimal> idUsuario { get; set; }
}

public partial class tResponsableInventario
{
    public decimal id { get; set; }
    public string Tipo { get; set; }
    public Nullable<decimal> idEmpresaInventario { get; set; }
}

public partial class tUsuario
{
    public decimal id { get; set; }
    public string Nombre { get; set; }
    public string Usuario { get; set; }
    public string Clave { get; set; }
    public string Mail { get; set; }
    public Nullable<byte> idCategoria { get; set; }
    public Nullable<byte> Papelera { get; set; }
}
