//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class NaexCRMEntities : DbContext
{
    public NaexCRMEntities()
        : base("name=NaexCRMEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tAccion> tAccion { get; set; }
    public virtual DbSet<tAsignacionResponsable> tAsignacionResponsable { get; set; }
    public virtual DbSet<tCategoria> tCategoria { get; set; }
    public virtual DbSet<tCategoriaInventario> tCategoriaInventario { get; set; }
    public virtual DbSet<tCliente> tCliente { get; set; }
    public virtual DbSet<tClientePosible> tClientePosible { get; set; }
    public virtual DbSet<tComentario> tComentario { get; set; }
    public virtual DbSet<tComentarioCompra> tComentarioCompra { get; set; }
    public virtual DbSet<tCompra> tCompra { get; set; }
    public virtual DbSet<tDatosTecnicos> tDatosTecnicos { get; set; }
    public virtual DbSet<tEmpresa> tEmpresa { get; set; }
    public virtual DbSet<tEstado> tEstado { get; set; }
    public virtual DbSet<tEstadoCompra> tEstadoCompra { get; set; }
    public virtual DbSet<tImagen> tImagen { get; set; }
    public virtual DbSet<tInventario> tInventario { get; set; }
    public virtual DbSet<tItem> tItem { get; set; }
    public virtual DbSet<tItem2> tItem2 { get; set; }
    public virtual DbSet<tLog> tLog { get; set; }
    public virtual DbSet<tManual> tManual { get; set; }
    public virtual DbSet<tModoResolucion> tModoResolucion { get; set; }
    public virtual DbSet<tNovedad> tNovedad { get; set; }
    public virtual DbSet<tPedido> tPedido { get; set; }
    public virtual DbSet<tPedidoMail> tPedidoMail { get; set; }
    public virtual DbSet<tPrioridad> tPrioridad { get; set; }
    public virtual DbSet<tProveedor> tProveedor { get; set; }
    public virtual DbSet<tRegistroAcceso> tRegistroAcceso { get; set; }
    public virtual DbSet<tResponsableEmpresa> tResponsableEmpresa { get; set; }
    public virtual DbSet<tUsuario> tUsuario { get; set; }
    public virtual DbSet<tResponsableInventario> tResponsableInventario { get; set; }
}
