//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCliente
    {
        public decimal id { get; set; }
        public Nullable<decimal> idEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Interno { get; set; }
        public string Mail { get; set; }
        public string Ip { get; set; }
        public string Password { get; set; }
        public string UsuarioRed { get; set; }
        public string PasswordRed { get; set; }
        public string ClaveSistema { get; set; }
        public Nullable<short> Papelera { get; set; }
        public Nullable<short> Autorizado { get; set; }
    }
}
