//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tComentario
    {
        public decimal id { get; set; }
        public Nullable<decimal> idPedido { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> VisibilidadCliente { get; set; }
        public string Tipo { get; set; }
    }
}
