//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tInventario
    {
        public decimal id { get; set; }
        public Nullable<decimal> idImagen { get; set; }
        public Nullable<decimal> idCategoria { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> empresa { get; set; }
        public string nro { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> cantUnidades { get; set; }
        public Nullable<decimal> idResponsable { get; set; }
    }
}
