//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tItem2
    {
        public decimal id { get; set; }
        public Nullable<decimal> idPedido { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Costo { get; set; }
        public string Precio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public Nullable<byte> idEstado { get; set; }
        public Nullable<decimal> idAprobo { get; set; }
    }
}
