//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tItem
    {
        public decimal id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> importeProveedor { get; set; }
        public Nullable<decimal> importeCliente { get; set; }
        public Nullable<decimal> idProveedor { get; set; }
        public Nullable<decimal> idCompra { get; set; }
        public Nullable<decimal> NroPedidoProveedor { get; set; }
    }
}
