//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tClientePosible
    {
        public decimal id { get; set; }
        public Nullable<decimal> idEmpresa { get; set; }
        public string rubro { get; set; }
        public string contacto { get; set; }
        public string puestoContacto { get; set; }
        public string contactoVinculado { get; set; }
        public string Mail { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public Nullable<decimal> idAccion1 { get; set; }
        public Nullable<short> idEstadoAccion1 { get; set; }
        public Nullable<decimal> idAccion2 { get; set; }
        public Nullable<short> idEstadoAccion2 { get; set; }
        public Nullable<decimal> idAccion3 { get; set; }
        public Nullable<short> idEstadoAccion3 { get; set; }
        public Nullable<decimal> idAccion4 { get; set; }
        public Nullable<short> idEstadoAccion4 { get; set; }
        public Nullable<decimal> idEstado { get; set; }
    }
}
