//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCompra
    {
        public decimal id { get; set; }
        public Nullable<decimal> idPedido { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public Nullable<decimal> idEmpresa { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public Nullable<decimal> idEstado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> totalProveedor { get; set; }
        public Nullable<decimal> totalCliente { get; set; }
        public Nullable<byte> iva { get; set; }
        public string codigo { get; set; }
        public Nullable<int> NewId { get; set; }
    }
}
