//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLog
    {
        public decimal id { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public string Accion { get; set; }
        public string Mensaje { get; set; }
    }
}
