//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPedido
    {
        public decimal id { get; set; }
        public Nullable<decimal> idEmpresa { get; set; }
        public Nullable<decimal> idCliente { get; set; }
        public Nullable<decimal> idUsuario { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaARealizar { get; set; }
        public Nullable<byte> Estado { get; set; }
        public Nullable<decimal> idCategoria { get; set; }
        public Nullable<byte> idPrioridad { get; set; }
        public Nullable<decimal> idAsignacionResponsable { get; set; }
        public Nullable<byte> idModoResolucion { get; set; }
    }
}
